# INTEL CONFIDENTIAL
# Copyright (C) 2022 Intel Corporation
# This software and the related documents are Intel copyrighted materials, 
# and your use of them is governed by the express license under which they 
# were provided to you ("License"). Unless the License provides otherwise, 
# you may not use, modify, copy, publish, distribute, disclose or transmit 
# this software or the related documents without Intel's prior written permission.
# This software and the related documents are provided as is, with no express 
# or implied warranties, other than those that are expressly stated in the License.

apiVersion: v1
kind: Service
metadata:
  name: audio-ingestion
  labels:
    app: audio-ingestion
spec:
  type: NodePort
  ports:
    - name: aud-port
      port: 50054
      targetPort: 50054
      nodePort: 30010
      protocol: TCP
  selector:
    app: audio-ingestion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-ingestion-server
  labels:
    app: audio-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-ingestion
  template:
    metadata:
      labels:
        app: audio-ingestion
    spec:
      volumes:
      - name: device-vol
        hostPath:
          path: /run/user/1000/pulse/native
      - name: audio-vol
        hostPath:
          path: /home/audio_ingestion/audio_data_samples/
      - name: cert-vol
        hostPath:
          path: /home/audio_ingestion/certificates/
      containers:
        - name: aud
          image: 'audio_ingestion:1.0'
          imagePullPolicy: IfNotPresent
          env:
          - name: http_proxy
            value: ""
          - name: https_proxy
            value: ""
          - name: env
            value: "dev"
          - name: run_mode
            value: "speech"
          - name: PYUSB_DEBUG_LEVEL
            value: "debug"
          - name: PULSE_SERVER
            value: "unix:/run/user/1000/pulse/native"
          ports:
            - containerPort: 50054
              name: aud-port
              protocol: TCP
          volumeMounts:
            - mountPath: /run/user/1000/pulse/native
              name: device-vol
            - mountPath: /home/audio_ingestion/audio_data_samples/
              name: audio-vol
            - mountPath: /home/audio_ingestion/server_certificates/
              name: cert-vol
          securityContext:
            runAsUser: 1000