# INTEL CONFIDENTIAL
# Copyright (C) 2022 Intel Corporation
# This software and the related documents are Intel copyrighted materials, 
# and your use of them is governed by the express license under which they 
# were provided to you ("License"). Unless the License provides otherwise, 
# you may not use, modify, copy, publish, distribute, disclose or transmit 
# this software or the related documents without Intel's prior written permission.
# This software and the related documents are provided as is, with no express 
# or implied warranties, other than those that are expressly stated in the License.

version: "3"
services:
  audio_ingestion:
    image: audio_ingestion:1.0
    environment:
      - http_proxy
      - https_proxy
      - env=dev
      #- run_mode=speech
      - run_mode=wav
      - PYUSB_DEBUG_LEVEL=debug
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      # - PULSE_SERVER=unix:/run/user/root/pulse/native
    # ports:
      # - "50054:50054"
    user: 1000:1000
    network_mode: "host" #extra thing from copied source code.
    # user: root:root
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
      # - /run/user/root/pulse/native:/run/user/root/pulse/native
      - ${PWD}/src/audio_data_samples/:/home/audio_ingestion/audio_data_samples/
      - ${PWD}/certificates/:/home/audio_ingestion/server_certificates/
