# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_ingestion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_ingestion.proto\x12\x0f\x61udio_ingestion\"\xe5\x01\n\x12\x42\x61tchIngestRequest\x12\x15\n\rsampling_rate\x18\x01 \x01(\x05\x12\x14\n\x0csample_width\x18\x02 \x01(\x05\x12\x13\n\x0b\x63hannel_num\x18\x03 \x01(\x05\x12\x18\n\x10\x63ompression_type\x18\x04 \x01(\t\x12\x19\n\x11\x61udio_device_name\x18\x05 \x01(\t\x12\x11\n\twake_word\x18\x06 \x01(\t\x12\x17\n\x0fnotifier_status\x18\x07 \x01(\x08\x12\x17\n\x0fmax_record_time\x18\x08 \x01(\x05\x12\x13\n\x0bvad_timeout\x18\t \x01(\x05\"\xfa\x01\n\x13StreamIngestRequest\x12\x15\n\rsampling_rate\x18\x01 \x01(\x05\x12\x14\n\x0csample_width\x18\x02 \x01(\x05\x12\x13\n\x0b\x63hannel_num\x18\x03 \x01(\x05\x12\x18\n\x10\x63ompression_type\x18\x04 \x01(\t\x12\x19\n\x11\x61udio_device_name\x18\x05 \x01(\t\x12\x11\n\twake_word\x18\x06 \x01(\t\x12\x17\n\x0fnotifier_status\x18\x07 \x01(\x08\x12\x17\n\x0fmax_record_time\x18\x08 \x01(\x05\x12\x13\n\x0bvad_timeout\x18\t \x01(\x05\x12\x12\n\nchunk_size\x18\n \x01(\x05\"\xb4\x02\n\x13\x41udioIngestResponse\x12\x14\n\x0c\x61udio_device\x18\x01 \x01(\t\x12\x42\n\x08msg_type\x18\x02 \x01(\x0e\x32\x30.audio_ingestion.AudioIngestResponse.MessageType\x12H\n\x0bmsg_control\x18\x03 \x01(\x0e\x32\x33.audio_ingestion.AudioIngestResponse.MessageControl\x12\x11\n\tmsg_audio\x18\x04 \x01(\x0c\"%\n\x0bMessageType\x12\t\n\x05\x61udio\x10\x00\x12\x0b\n\x07\x63ontrol\x10\x01\"?\n\x0eMessageControl\x12\x08\n\x04wake\x10\x00\x12\t\n\x05sleep\x10\x01\x12\x0e\n\naudio_data\x10\x02\x12\x08\n\x04quit\x10\x03\x32\xe0\x01\n\x0e\x41udioIngestion\x12\x65\n\x14\x41udioIngestBatchInit\x12#.audio_ingestion.BatchIngestRequest\x1a$.audio_ingestion.AudioIngestResponse\"\x00\x30\x01\x12g\n\x15\x41udioIngestStreamInit\x12$.audio_ingestion.StreamIngestRequest\x1a$.audio_ingestion.AudioIngestResponse\"\x00\x30\x01\x62\x06proto3')



_BATCHINGESTREQUEST = DESCRIPTOR.message_types_by_name['BatchIngestRequest']
_STREAMINGESTREQUEST = DESCRIPTOR.message_types_by_name['StreamIngestRequest']
_AUDIOINGESTRESPONSE = DESCRIPTOR.message_types_by_name['AudioIngestResponse']
_AUDIOINGESTRESPONSE_MESSAGETYPE = _AUDIOINGESTRESPONSE.enum_types_by_name['MessageType']
_AUDIOINGESTRESPONSE_MESSAGECONTROL = _AUDIOINGESTRESPONSE.enum_types_by_name['MessageControl']
BatchIngestRequest = _reflection.GeneratedProtocolMessageType('BatchIngestRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATCHINGESTREQUEST,
  '__module__' : 'audio_ingestion_pb2'
  # @@protoc_insertion_point(class_scope:audio_ingestion.BatchIngestRequest)
  })
_sym_db.RegisterMessage(BatchIngestRequest)

StreamIngestRequest = _reflection.GeneratedProtocolMessageType('StreamIngestRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGESTREQUEST,
  '__module__' : 'audio_ingestion_pb2'
  # @@protoc_insertion_point(class_scope:audio_ingestion.StreamIngestRequest)
  })
_sym_db.RegisterMessage(StreamIngestRequest)

AudioIngestResponse = _reflection.GeneratedProtocolMessageType('AudioIngestResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOINGESTRESPONSE,
  '__module__' : 'audio_ingestion_pb2'
  # @@protoc_insertion_point(class_scope:audio_ingestion.AudioIngestResponse)
  })
_sym_db.RegisterMessage(AudioIngestResponse)

_AUDIOINGESTION = DESCRIPTOR.services_by_name['AudioIngestion']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATCHINGESTREQUEST._serialized_start=43
  _BATCHINGESTREQUEST._serialized_end=272
  _STREAMINGESTREQUEST._serialized_start=275
  _STREAMINGESTREQUEST._serialized_end=525
  _AUDIOINGESTRESPONSE._serialized_start=528
  _AUDIOINGESTRESPONSE._serialized_end=836
  _AUDIOINGESTRESPONSE_MESSAGETYPE._serialized_start=734
  _AUDIOINGESTRESPONSE_MESSAGETYPE._serialized_end=771
  _AUDIOINGESTRESPONSE_MESSAGECONTROL._serialized_start=773
  _AUDIOINGESTRESPONSE_MESSAGECONTROL._serialized_end=836
  _AUDIOINGESTION._serialized_start=839
  _AUDIOINGESTION._serialized_end=1063
# @@protoc_insertion_point(module_scope)
