# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_ingestion_pb2 as audio__ingestion__pb2


class AudioIngestionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AudioIngestBatchInit = channel.unary_stream(
                '/audio_ingestion.AudioIngestion/AudioIngestBatchInit',
                request_serializer=audio__ingestion__pb2.BatchIngestRequest.SerializeToString,
                response_deserializer=audio__ingestion__pb2.AudioIngestResponse.FromString,
                )
        self.AudioIngestStreamInit = channel.unary_stream(
                '/audio_ingestion.AudioIngestion/AudioIngestStreamInit',
                request_serializer=audio__ingestion__pb2.StreamIngestRequest.SerializeToString,
                response_deserializer=audio__ingestion__pb2.AudioIngestResponse.FromString,
                )


class AudioIngestionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AudioIngestBatchInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AudioIngestStreamInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AudioIngestBatchInit': grpc.unary_stream_rpc_method_handler(
                    servicer.AudioIngestBatchInit,
                    request_deserializer=audio__ingestion__pb2.BatchIngestRequest.FromString,
                    response_serializer=audio__ingestion__pb2.AudioIngestResponse.SerializeToString,
            ),
            'AudioIngestStreamInit': grpc.unary_stream_rpc_method_handler(
                    servicer.AudioIngestStreamInit,
                    request_deserializer=audio__ingestion__pb2.StreamIngestRequest.FromString,
                    response_serializer=audio__ingestion__pb2.AudioIngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio_ingestion.AudioIngestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioIngestion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AudioIngestBatchInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/audio_ingestion.AudioIngestion/AudioIngestBatchInit',
            audio__ingestion__pb2.BatchIngestRequest.SerializeToString,
            audio__ingestion__pb2.AudioIngestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AudioIngestStreamInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/audio_ingestion.AudioIngestion/AudioIngestStreamInit',
            audio__ingestion__pb2.StreamIngestRequest.SerializeToString,
            audio__ingestion__pb2.AudioIngestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
