apiVersion: v1
kind: Service
metadata:
  name: tts
  labels:
    app: tts
spec:
  type: NodePort
  ports:
    - name: tts-port
      port: 50052
      targetPort: 50052
      nodePort: 30009
      protocol: TCP
  selector:
    app: tts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-server
  labels:
    app: tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts
  template:
    metadata:
      labels:
        app: tts
    spec:
      containers:
        - name: tts
          image: 'tts:1.0'
          imagePullPolicy: IfNotPresent
          env:
          - name: http_proxy
            value: http://proxy.iind.intel.com:911
          - name: https_proxy
            value: http://proxy.iind.intel.com:911
          - name: cache
            value: "True"
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/health_state.txt
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 300
            successThreshold: 1
            failureThreshold: 30
          ports:
            - containerPort: 50052
              name: tts-port
              protocol: TCP