# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
version: "3"
services:
  server_speaker_diarization:
    build: .
    environment:
      # for server-service-speaker_diarization
      - ZMQ_TOPIC_SD=audio_for_speaker_diarization
      - ZMQ_TYPE_SD=zmq_tcp
      - ZMQ_HOST_IP_SD=127.0.0.1
      - ZMQ_HOST_PORT_SD=3000
      - PYTHONUNBUFFERED= 1
      - ZMQ_TOPIC_TS=text_summarization
      - ZMQ_TYPE_TS=zmq_tcp
      - ZMQ_HOST_IP_TS=127.0.0.1
      - ZMQ_HOST_PORT_TS=3001
      - KALDI_ROOT=/home/speaker-diarization/tmp/kaldi
    network_mode: "host"
    # user: 1000:1000
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native